~/dev/py/xlattice_py

2015-05-18
    * mkdir_p needs testing
2015-05-17
    * git push appears to have failed, but with no meaningful error     * FIXED
        message.  xlattice_py on github has myData/ myU1/ myU2/         * FIXED
        trash, which it shouldn't.  URGENT need to reconcile what       * FIXED
        we have here and what is on github                              * FIXED

2015-05-15
    * need myData, myU1, myU2 in .gitignore.local                       * DONE
    * add DecimalVersion.step{Major,Minor,Decimal,Micro}                * DONE
        - and test                                                      * DONE
    * need tests for xlattice/u                                         * DONE

2015-05-14
    * myData/ myU1/ myU2 need to be added to .gitignore,
        which requires a .gitignore-local functionality
    * move SHA1* constants to xlattice package                          * DONE
    * need test for xlattice.ui (passwdStrength)

2015-05-11
    * gittifyProject.sh  xlattice_py >& junk.gittify                    * DONE
    * ghpTheProject.sh   xlattice_py >& junk.ghp                        * DONE
        - seems OK but index.html at jddixon.github.io/xlattice_py      * OK...
            is 'dummy index' and LICENSE.html gets a 404                * OK...
    * splitTheProject.sh xlattice_py                                    * OK...
        - FAILED because sharedev subdir had not been deleted           * OK...
        - manually fixed but still see 'dummy index' on github.io       * OK...
        - touched *.html in sharedev and then git commit from           * OK...
            sharedev; this worked                                       * OK...

FROM ~/dev/py/u/TODO ================================================

2015-03-19
    * if eg myU2/tmp does not exist, the library must create it         * DONE

2012-07-28 
    * FIX: testU256x256.py fails (because testU/tmp does not exist?)    * DONE

2012-07-02
    * added u.getData(uPath, key); needs to be tested

2012-06-02
    * BUG found when attempting to run upaxUpdateNodeID on test:
        copyAndPut invokes put which attempts to rename a temporary 
        file into /var/Upax; this yields an 'invalid cross-device link' 
        error 
        -- FIXED?

    * BUG observed but hasn't caused an error yet: u.put expects input
        file to be in the same file system.

    * lock directory /tmp/u must be world-writeable; the current 
        implementation creates world-writeable leaf directories but 
        intermediate directories may not be such

2012-05-30
    * consider adding keyless copyAndPut(), put(), and putData(); these 
        would have names like putKeyless(), would have no content key
        parameter, but would still return the content key

    * Compare code from xlshadow 
